apiVersion: v1
kind: Service
metadata:
  name: ai-webscraper-service
spec:
  selector:
    app: ai-webscraper
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: NodePort
